public with sharing class ConstantsClass {
    public static final string Stage_Closed_Won = 'Closed Won';
    public static final string Case_Status_New = 'New';
    public static final string Case_Status_Closed = 'Closed';
    public static final String Opportunity_Business_Record_Type = 'Business'; 
    public static final string Account_Manager_Role = 'Account Manager';
    public static final String Stage_Qualification = 'Qualification';
    public static final string Stage_Value_Proposition = 'Value Proposition';
    public static final String Case_Priority = 'High';
    public Static final String Case_Origin = 'Email';
    public Static final String Opportunity_Type_Upgrade = 'Existing Customer - Upgrade';
    public Static final String Channel_Manager_Role = 'Channel Manager';
    public Static final String Executive_Sponsor_Role = 'Executive Sponsor';
    public Static final String Lead_Qualifier_Role = 'Lead Qualifier';
    public static final String ROLE_LEAD_QUALIFIER = 'Lead Qualifier';
    public static final String ROLE_SALES_MANAGER = 'Sales Manager';
    public static final String ROLE_SALES_REPOSITER = 'Pre-Sales Consultant';
    public static final String ROLE_RESALE_CONTRACTOR = 'Sales Rep';
    public static final String Technical_Engineer_Role = 'Technical Engineer';
    public Static final String Technical_Issue_Reason = 'Technical Issue';
    public Static final String Technical_Issue_RecordType = 'Technical_issue';
    public Static final String Technical_Queue = 'Technical_queue';
}